spring:
  application:
    name: PdfGen

  datasource:

    url: jdbc:postgresql://localhost:5438/pdfgen
    username: postgress
    password: postgress


  jpa:
    show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
