spring:
  application:
    name: PdfGen

  datasource:
    url: jdbc:h2:mem:test00
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
      console: true
      path: /h2-console

  jpa:
    show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
